/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_healthz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/world": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Observe */
    get: operations["observe_api_world_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/actions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Act */
    post: operations["act_api_actions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Events */
    get: operations["events_api_events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/incidents/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start Incident */
    post: operations["start_incident_api_incidents_runs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/incidents/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Observe Incident */
    get: operations["observe_incident_api_incidents_runs__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/incidents/runs/{run_id}/tools": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Incident Tool */
    post: operations["incident_tool_api_incidents_runs__run_id__tools_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/incidents/runs/{run_id}/proposals/validate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Validate Proposal */
    post: operations["validate_proposal_api_incidents_runs__run_id__proposals_validate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/incidents/runs/{run_id}/proposals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request Execution */
    post: operations["request_execution_api_incidents_runs__run_id__proposals_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/incidents/runs/{run_id}/approval": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve Execution */
    post: operations["approve_execution_api_incidents_runs__run_id__approval_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/incidents/runs/{run_id}/apply": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Apply Execution */
    post: operations["apply_execution_api_incidents_runs__run_id__apply_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Action */
    Action: {
      /**
       * Action Id
       * Format: uuid
       */
      action_id: string;
      /** Actor Id */
      actor_id: string;
      /**
       * Type
       * @constant
       */
      type: "move";
      /** Dx */
      dx: number;
      /** Dy */
      dy: number;
    };
    /** ActionResult */
    ActionResult: {
      world: components["schemas"]["WorldState"];
      /** Events */
      events: components["schemas"]["Event"][];
      event: components["schemas"]["Event"];
    };
    /** ApplyRequest */
    ApplyRequest: {
      /**
       * Action Id
       * Format: uuid
       */
      action_id: string;
      /** Proposal Hash */
      proposal_hash: string;
      /** Expected Revision */
      expected_revision: number;
    };
    /** ApprovalRequest */
    ApprovalRequest: {
      /**
       * Action Id
       * Format: uuid
       */
      action_id: string;
      /** Proposal Hash */
      proposal_hash: string;
      /** Expected Revision */
      expected_revision: number;
      /** Approve */
      approve: boolean;
    };
    /** Entity */
    Entity: {
      /** Id */
      id: string;
      position: components["schemas"]["Position"];
    };
    /** Event */
    Event: {
      /**
       * Event Id
       * Format: uuid
       */
      event_id: string;
      action: components["schemas"]["Action"];
      /**
       * Status
       * @enum {string}
       */
      status: "success" | "failure";
      /**
       * Reason
       * @enum {string}
       */
      reason: "moved" | "out_of_bounds" | "unknown_actor" | "invalid_move";
      before: components["schemas"]["Position"] | null;
      after: components["schemas"]["Position"] | null;
      /**
       * World Id
       * Format: uuid
       */
      world_id: string;
      /** World Revision */
      world_revision: number;
    };
    /** EventHistory */
    EventHistory: {
      world: components["schemas"]["WorldState"];
      /** Events */
      events: components["schemas"]["Event"][];
    };
    /** EvidenceItem */
    EvidenceItem: {
      /** Ref */
      ref: string;
      /** Source */
      source: string;
      /** Timestamp */
      timestamp: string;
      /** Data */
      data: {
        [key: string]: unknown;
      };
    };
    /** ExecutionRequest */
    ExecutionRequest: {
      /**
       * Action Id
       * Format: uuid
       */
      action_id: string;
      proposal: components["schemas"]["RecoveryProposal"];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** IncidentRunRequest */
    IncidentRunRequest: {
      /** Scenario Number */
      scenario_number: number;
    };
    /** IncidentSnapshot */
    IncidentSnapshot: {
      /** Scenario Number */
      scenario_number: number;
      summary: components["schemas"]["IncidentSummary"];
      /** Services */
      services: {
        [key: string]: {
          [key: string]: unknown;
        };
      };
      /** Evidence */
      evidence: components["schemas"]["EvidenceItem"][];
      pending_proposal?: components["schemas"]["RecoveryProposal"] | null;
      /** Proposal Hash */
      proposal_hash?: string | null;
      /** Approved Hash */
      approved_hash?: string | null;
      /**
       * Applied Changes
       * @default []
       */
      applied_changes: components["schemas"]["RecoveryChange"][];
    };
    /** IncidentSummary */
    IncidentSummary: {
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string;
      /** Revision */
      revision: number;
      /** Accepted */
      accepted: number;
      /** Incomplete */
      incomplete: number;
      /** Completed */
      completed: number;
      /** Duplicate Count */
      duplicate_count: number;
      /**
       * State
       * @enum {string}
       */
      state:
        "investigating" | "waiting_approval" | "applying" | "verifying" | "recovered" | "stopped";
    };
    /** IncidentToolRequest */
    IncidentToolRequest: {
      /**
       * Tool
       * @enum {string}
       */
      tool:
        | "observe_system"
        | "query_events"
        | "inspect_queue"
        | "read_service_config"
        | "list_changes"
        | "search_knowledge"
        | "probe_dependency"
        | "advance_and_verify"
        | "lookup_action_status";
      /** Args */
      args?: {
        [key: string]: unknown;
      };
    };
    /** IncidentToolResult */
    IncidentToolResult: {
      /** Tool */
      tool: string;
      /**
       * Status
       * @enum {string}
       */
      status: "success" | "failure" | "denied";
      summary: components["schemas"]["IncidentSummary"];
      /** Evidence */
      evidence: components["schemas"]["EvidenceItem"][];
      /** Error */
      error?: string | null;
    };
    /** Position */
    Position: {
      /** X */
      x: number;
      /** Y */
      y: number;
    };
    /** ProposalResult */
    ProposalResult: {
      /**
       * Status
       * @enum {string}
       */
      status:
        "valid" | "invalid" | "waiting_approval" | "approved" | "applied" | "failure" | "stale";
      /** Proposal Hash */
      proposal_hash: string;
      summary: components["schemas"]["IncidentSummary"];
      /**
       * Violations
       * @default []
       */
      violations: string[];
      /**
       * Event Refs
       * @default []
       */
      event_refs: string[];
    };
    /** RecoveryChange */
    RecoveryChange: {
      /**
       * Operation
       * @enum {string}
       */
      operation: "set_config" | "select_deployment" | "requeue";
      /**
       * Service
       * @enum {string}
       */
      service: "worker" | "carrier" | "queue";
      /** Key */
      key?: string | null;
      /** Value */
      value?: string | null;
      /**
       * Order Ids
       * @default []
       */
      order_ids: string[];
      /** Expected State */
      expected_state?: string | null;
    };
    /** RecoveryProposal */
    RecoveryProposal: {
      /** Expected Revision */
      expected_revision: number;
      /** Diagnosis */
      diagnosis: string;
      /** Evidence Refs */
      evidence_refs: string[];
      /** Changes */
      changes: components["schemas"]["RecoveryChange"][];
      /** Rollback */
      rollback: string;
      /**
       * Verification Ticks
       * @default 4
       * @constant
       */
      verification_ticks: 4;
      /**
       * Canary Count
       * @default 2
       * @constant
       */
      canary_count: 2;
      /**
       * Verification Scope
       * @default affected_orders_and_canaries
       * @constant
       */
      verification_scope: "affected_orders_and_canaries";
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** WorldState */
    WorldState: {
      /**
       * World Id
       * Format: uuid
       */
      world_id: string;
      /** Revision */
      revision: number;
      /** Width */
      width: number;
      /** Height */
      height: number;
      /** Entities */
      entities: components["schemas"]["Entity"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  observe_api_world_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorldState"];
        };
      };
    };
  };
  act_api_actions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Action"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActionResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  events_api_events_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventHistory"];
        };
      };
    };
  };
  start_incident_api_incidents_runs_post: {
    parameters: {
      query?: never;
      header?: {
        "x-lab-capability"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IncidentRunRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IncidentSnapshot"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  observe_incident_api_incidents_runs__run_id__get: {
    parameters: {
      query?: never;
      header?: {
        "x-lab-capability"?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IncidentSnapshot"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  incident_tool_api_incidents_runs__run_id__tools_post: {
    parameters: {
      query?: never;
      header?: {
        "x-lab-capability"?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IncidentToolRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IncidentToolResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  validate_proposal_api_incidents_runs__run_id__proposals_validate_post: {
    parameters: {
      query?: never;
      header?: {
        "x-lab-capability"?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecoveryProposal"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProposalResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  request_execution_api_incidents_runs__run_id__proposals_post: {
    parameters: {
      query?: never;
      header?: {
        "x-lab-capability"?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExecutionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProposalResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  approve_execution_api_incidents_runs__run_id__approval_post: {
    parameters: {
      query?: never;
      header?: {
        "x-lab-capability"?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApprovalRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProposalResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  apply_execution_api_incidents_runs__run_id__apply_post: {
    parameters: {
      query?: never;
      header?: {
        "x-lab-capability"?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApplyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProposalResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
