/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/world": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Observe */
    get: operations["observe_api_world_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/actions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Act */
    post: operations["act_api_actions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Action */
    Action: {
      /**
       * Action Id
       * Format: uuid
       */
      action_id: string;
      /** Actor Id */
      actor_id: string;
      /**
       * Type
       * @constant
       */
      type: "move";
      /** Dx */
      dx: number;
      /** Dy */
      dy: number;
    };
    /** ActionResult */
    ActionResult: {
      event: components["schemas"]["Event"];
      world: components["schemas"]["WorldState"];
    };
    /** Entity */
    Entity: {
      /** Id */
      id: string;
      position: components["schemas"]["Position"];
    };
    /** Event */
    Event: {
      /**
       * Event Id
       * Format: uuid
       */
      event_id: string;
      action: components["schemas"]["Action"];
      /**
       * Status
       * @enum {string}
       */
      status: "success" | "failure";
      /**
       * Reason
       * @enum {string}
       */
      reason: "moved" | "out_of_bounds" | "unknown_actor" | "invalid_move";
      before: components["schemas"]["Position"] | null;
      after: components["schemas"]["Position"] | null;
      /**
       * World Id
       * Format: uuid
       */
      world_id: string;
      /** World Revision */
      world_revision: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Position */
    Position: {
      /** X */
      x: number;
      /** Y */
      y: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** WorldState */
    WorldState: {
      /**
       * World Id
       * Format: uuid
       */
      world_id: string;
      /** Revision */
      revision: number;
      /** Width */
      width: number;
      /** Height */
      height: number;
      /** Entities */
      entities: components["schemas"]["Entity"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  observe_api_world_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorldState"];
        };
      };
    };
  };
  act_api_actions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Action"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActionResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
